// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0044:Modifizierer \"readonly\" hinzufügen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Encrypted_Notebook.Page.pageCreateUser.DBMgr")]
[assembly: SuppressMessage("Style", "IDE0044:Modifizierer \"readonly\" hinzufügen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Encrypted_Notebook.Page.pageCreateUser.mw")]
[assembly: SuppressMessage("CodeQuality", "IDE0052:Ungelesene private Member entfernen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Encrypted_Notebook.Page.pageDatabase404.mw")]
[assembly: SuppressMessage("Style", "IDE0044:Modifizierer \"readonly\" hinzufügen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Encrypted_Notebook.Page.pageDatabase404.mw")]
[assembly: SuppressMessage("Style", "IDE0044:Modifizierer \"readonly\" hinzufügen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Encrypted_Notebook.Page.pageLoginServer.DBMgr")]
[assembly: SuppressMessage("Style", "IDE0044:Modifizierer \"readonly\" hinzufügen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Encrypted_Notebook.Page.pageLoginServer.mw")]
[assembly: SuppressMessage("Style", "IDE0044:Modifizierer \"readonly\" hinzufügen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Encrypted_Notebook.Page.pageLoginUser.DBMgr")]
[assembly: SuppressMessage("Style", "IDE0044:Modifizierer \"readonly\" hinzufügen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Encrypted_Notebook.Page.pageLoginUser.mw")]
[assembly: SuppressMessage("Style", "IDE0044:Modifizierer \"readonly\" hinzufügen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Encrypted_Notebook.Page.pageNotebook.DBMgr")]
[assembly: SuppressMessage("Style", "IDE0044:Modifizierer \"readonly\" hinzufügen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Encrypted_Notebook.Page.pageNotebook.mw")]
[assembly: SuppressMessage("Style", "IDE0044:Modifizierer \"readonly\" hinzufügen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Encrypted_Notebook.Page.pageServerConfigure.DBMgr")]
[assembly: SuppressMessage("Style", "IDE0044:Modifizierer \"readonly\" hinzufügen", Justification = "<Ausstehend>", Scope = "member", Target = "~F:Encrypted_Notebook.Page.pageServerConfigure.mw")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Class.DatabaseManager.checkIfServerIsConfigured~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Class.DatabaseManager.checkIfUserExist(System.String)~System.Int32")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Class.DatabaseManager.connectionString(System.String,System.String,System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Class.DatabaseManager.createNotebook(System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Class.DatabaseManager.createUser(System.String,System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Class.DatabaseManager.dbConnect~System.String")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Class.DatabaseManager.dbDisconnect~System.String")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Class.DatabaseManager.dbError~System.String")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Class.DatabaseManager.deleteNotebook(System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Class.DatabaseManager.loadNotebooks~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Class.DatabaseManager.loginUser(System.String,System.String)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Class.DatabaseManager.readNotes~System.String")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Class.DatabaseManager.writeNotes(System.String)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Page.pageCreateUser.bttn_create_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Page.pageLoginServer.bttn_login_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Page.pageLoginServer.bttn_save_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Page.pageLoginUser.bttn_createUser_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Page.pageLoginUser.bttn_login_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Page.pageNotebook.bttn_logout_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Page.pageNotebook.bttn_notebookCreate_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Page.pageNotebook.bttn_notebookDelete_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Page.pageNotebook.bttn_notesSave_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Page.pageNotebook.lb_notebooks_SelectionChanged(System.Object,System.Windows.Controls.SelectionChangedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE0059:Unnötige Zuweisung eines Werts.", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Page.pageNotebook.LoadNotebooks")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "member", Target = "~M:Encrypted_Notebook.Page.pageServerConfigure.bttn_configure_Click(System.Object,System.Windows.RoutedEventArgs)")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:Encrypted_Notebook.Page.pageDatabase404")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:Encrypted_Notebook.Page.pageNotebook")]
[assembly: SuppressMessage("Style", "IDE1006:Benennungsstile", Justification = "<Ausstehend>", Scope = "type", Target = "~T:Encrypted_Notebook.Page.pageServerConfigure")]
